name: Build

on:
  push:
    branches: [ "main", "next" ]
    tags: [ '*' ]

jobs:
  build:
    runs-on: fedora-latest
    container: 
        image: ghcr.io/lex-ibm/electron-ppc64le-build-scripts:next
        volumes:
            - /opt/electron-git-cache:/opt/electron-git-cache
        options: -v /opt/electron-src-overlay:/opt/electron-src-overlay:O
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Build Script
        env:
          GIT_CACHE_PATH: /opt/electron-git-cache/
        run: ./build-electron.sh
