name: Docker

on:
  push:
    branches: [ "main", "next" ]
    tags: [ '*' ]

jobs:
  build:
    runs-on: fedora-latest
    container: 
      image: ghcr.io/lex-ibm/electron-ppc64le-build-scripts:next
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Build Script
        run: ./build-electron.sh
